package commInfra;

/**
 * Message Types
 */

public enum MessageType {
    GETINQUEUE,
    PREPAREFORPASSBOARDING,
    WAITINQUEU,
    CHECKDOCUMENTS,
    SHOWDOCUMENTS,
    WAITFORNEXTPASSENGER,
    BOARDTHEPLANE,
    GETINF,
    SETINF,
    REPORTFINALREPORT,
    PARKATTRANSFERGATE,
    INFORMPLANEREADYFORBOARDING,
    WAITFORNEXTFLIGHT,
    WAITFORALLBOARDING,
    INFORMPLANEREADYTOTAKEOFF,
    WAITFORENDOFFLIGHT,
    ANNOUNCEARRIVAL,
    LEAVETHEPLANE,
    GETPTAL,
    INCPTAL,
    SETPASSENGERSTATE,
    SETHOSTESSSTATE,
    SETPILOTSTATE,
    REPORTINITIALSTATUS,
    REPORTSTATUS,
    REPORTFINALINFO
}
